# @format
---
pr: none

trigger:
  batch: false
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

pool:
  vmImage: ubuntu-20.04

variables:
  AZ_CLI_VERSION: 2.16.0
  JQ_VERSION: 1.6
  SOPS_VERSION: 3.6.1
  GOLANG_VERSION: 1.15.6
  SHFMT_VERSION: 3.2.1
  SHELLCHECK_VERSION: 0.7.1
  YAMLLINT_VERSION: 1.25.0
  HELM_VERSION: 3.4.1
  TERRAFORM_VERSION: 0.14.2
  DOCKER_VERSION: 20.10.0
  DOCKER_COMPOSE_VERSION: 1.27.4
  HADOLINT_VERSION: 1.19.0
  CHART_RELEASER_VERSION: 1.1.1

stages:
  - template: .azure-pipelines/templates/01_lint.yaml
  - template: .azure-pipelines/templates/02_docker_build.yaml
  - template: .azure-pipelines/templates/03_helm_push.yaml
  - template: .azure-pipelines/templates/04_docker_push.yaml
