# @format
---
- name: set fact k8s_auth_kubeconfig
  set_fact:
    k8s_auth_kubeconfig: "{{ kubeconfig_filepath | expanduser }}"

- name: set fact kubeconfig_contents
  set_fact:
    kubeconfig_contents: "{{ lookup('file', k8s_auth_kubeconfig) | from_yaml }}"
  no_log: true

- name: set fact k8s_auth_context
  set_fact:
    k8s_auth_context: '{{ kubeconfig_contents["current-context"] }}'
