# @format
---
stages:
  - stage: lint
    displayName: Lint codebase
    condition: and(
      ne(variables['Build.SourceBranch'], 'refs/heads/master'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
      )
    dependsOn: []
    jobs:
      - job: lint
        displayName: Lint codebase
        condition: always()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Lint codebase
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make lint_all
