# @format
---
stages:
  - stage: docker_build
    displayName: Build images
    condition: and(
      ne(variables['Build.SourceBranch'], 'refs/heads/master'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
      )
    dependsOn: [lint]
    jobs:
      - job: build_saleor_core
        displayName: Build saleor-core image
        condition: always()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Build saleor-core image
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make build_saleor_core

      - job: build_saleor_core_dev
        displayName: Build saleor-core-dev image
        condition: always()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Build saleor-core-dev image
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make build_saleor_core_dev

      - job: build_saleor_dashboard
        displayName: Build saleor-dashboard image
        condition: always()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Build saleor-dashboard image
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make build_saleor_dashboard

      - job: build_saleor_storefront
        displayName: Build saleor-storefront image
        condition: always()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Build saleor-storefront image
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make build_saleor_storefront
