import os

# Gunicorn Settings, see https://docs.gunicorn.org/en/stable/settings.html#settings
reload = False
check_config = False
accesslog = '-'
disable_redirect_access_to_syslog = True
access_log_format = '"remote_addr": "%(h)s", "status":"%(s)s", "method":"%(m)s", "url":"%(U)s%(q)s", "request_id":"%({X-Request-Id}i)s"}, "request_time_msec":"%(D)s"'
errorlog = '-'
loglevel = os.getenv("GUNICORN_LOG_LEVEL", "-")
capture_output = False
# logger_class = gunicorn.glogging.Logger
logconfig = None
logconfig_dict = {}
statsd_host = None
limit_request_line = 4094
limit_request_fields = 20
limit_request_field_size = 4094
preload_app = False
sendfile = None
reuse_port = False
daemon = False
raw_env = []
pidfile = None
worker_tmp_dir = None
# user = 1005
# group = 205
# umask = 0
initgroups = False
tmp_upload_dir = None
# secure_scheme_headers = {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
forwarded_allow_ips = os.getenv("GUNICORN_FORWARDED_ALLOW_IPS", "127.0.0.1")
pythonpath = None
paste = None
proxy_allow_ips = os.getenv("GUNICORN_PROXY_ALLOW_IPS", "127.0.0.1")
raw_paste_global_conf = []
strip_header_spaces = False
bind = os.getenv("GUNICORN_BIND_HOST", "127.0.0.1") + ':' + os.getenv("GUNICORN_BIND_PORT", "8000")
backlog = os.getenv("GUNICORN_BACKLOG", "2048")
workers = os.getenv("GUNICORN_WORKER_PROCESSES", "1")
worker_class = os.getenv("GUNICORN_WORKER_CLASS", "uvicorn.workers.UvicornWorker")
threads = os.getenv("GUNICORN_THREADS_PER_WORKER", "1")
worker_connections = os.getenv("GUNICORN_MAX_WORKER_CONNECTIONS", "1000")
max_requests = 0
max_requests_jitter = 0
timeout = os.getenv("GUNICORN_SILENT_WORKER_TIMEOUT", "30")
graceful_timeout = os.getenv("GUNICORN_WORKER_RESTART_GRACEFUL_TIMEOUT", "30")
keepalive = os.getenv("GUNICORN_CONNECTION_KEEP_ALIVE", "2")
